---
- name: noaa environment variables
  ansible.builtin.template:
    src: noaa-v2.conf.j2
    dest: "{{ ansible_user_dir }}/.noaa-v2.conf"
    owner: "{{ ansible_user_id }}"
    mode: '0644'

- name: predict directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.predict"
    owner: "{{ ansible_user_id }}"
    mode: '0755'
    state: directory

- name: predict config file
  ansible.builtin.template:
    src: predict.qth.j2
    dest: "{{ ansible_user_dir }}/.predict/predict.qth"
    owner: "{{ ansible_user_id }}"
    mode: '0644'

- name: wxtoimg config file
  ansible.builtin.template:
    src: wxtoimgrc.j2
    dest: "{{ ansible_user_dir }}/.wxtoimgrc"
    owner: "{{ ansible_user_id }}"
    mode: '0644'

- name: wxtoimg license terms acceptance file
  ansible.builtin.copy:
    src: wxtoimglic
    dest: "{{ ansible_user_dir }}/.wxtoimglic"
    owner: "{{ ansible_user_id }}"
    mode: '0644'

- name: log directory for raspberry-noaa-v2 logs
  ansible.builtin.file:
    path: /var/log/raspberry-noaa-v2
    owner: "{{ ansible_user_id }}"
    mode: 0755
    state: directory
  become: true

- name: logrotate settings for raspberry-noaa-v2 logs
  ansible.builtin.copy:
    src: logrotate-settings
    dest: /etc/logrotate.d/raspberry-noaa-v2
    owner: root
    group: root
    mode: '0644'
  become: true

- name: gnuradio home directories
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/{{ item }}"
    owner: "{{ ansible_user_id }}"
    mode: '0755'
    state: directory
  loop:
    - .gnuradio
    - .gnuradio/prefs

- name: gnuradio prefs file
  ansible.builtin.copy:
    src: vmcircbuf_default_factory
    dest: "{{ ansible_user_dir }}/.gnuradio/prefs/vmcircbuf_default_factory"
    owner: "{{ ansible_user_id }}"
    mode: '0644'

- name: disable wifi power mgmt script
  become: yes
  ansible.builtin.copy:
    src: disable-wifi-powermgmt.sh
    dest: /usr/local/sbin/disable-wifi-powermgmt.sh
    owner: root
    group: root
    mode: '0755'
  when: disable_wifi_power_mgmt

- name: disable wifi power mgmt service definition
  ansible.builtin.copy:
    src: disable-wifi-powermgmt.service
    dest: /etc/systemd/system/disable-wifi-powermgmt.service
    owner: root
    group: root
    mode: '0644'
  become: true
  when: disable_wifi_power_mgmt

- name: enable systemd wifi power management disable service
  ansible.builtin.systemd:
    name: disable-wifi-powermgmt
    enabled: true
    daemon_reload: true
  become: true
  when: disable_wifi_power_mgmt

- name: annotation directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/config/annotation"
    state: directory
    owner: pi
    group: pi
    mode: 0755

- name: annotation files (sample for modification)
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ ansible_user_dir }}/raspberry-noaa-v2/config/annotation/{{ item.dest | default(item.src) }}"
    owner: pi
    group: pi
    mode: 0644
    force: false
  loop:
    - src: annotation.html.j2_file
      dest: annotation.html.j2
    - src: raspberry-noaa-v2-logo.png
