---
- name: install dependencies
  ansible.builtin.package:
    name:
      - at
      - bc
      - cmake
      - ffmpeg
      - gmic
      - gnuradio
      - gr-osmosdr
      - imagemagick
      - jq
      - libatlas-base-dev
      - libgfortran5
      - libjpeg9
      - libjpeg9-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libsox-fmt-mp3
      - libusb-1.0-0
      - libusb-1.0-0-dev
      - libxft-dev
      - libxft2
      - predict
      - python-setuptools
      - python3-pip
      - socat
      - sox
      - sqlite3
    state: present
  become: true

- name: install wkhtmltox (wkhtmltoimg)
  ansible.builtin.apt:
    deb: https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.raspberrypi.buster_armhf.deb
    state: present
  become: true
