---
- name: install mpack and msmtp if emailing is enabled
  ansible.builtin.package:
    name:
      - mpack
      - msmtp
      - msmtp-mta
    state: present
  become: true

- name: drop template email msmtp config file
  copy:
    src: msmtprc
    dest: "{{ ansible_user_dir }}/.msmtprc"
    owner: "{{ ansible_user_id }}"
    mode: '0600'
    force: false

- name: create an msmtp log directory
  file:
    path: /var/log/msmtp
    owner: "{{ ansible_user_id }}"
    mode: '0757'
    state: directory
  become: true

- name: logrotate settings for msmtp
  copy:
    src: email-logrotate-settings
    dest: /etc/logrotate.d/msmtp
    owner: root
    group: root
    mode: '0644'
  become: true
