---
# environment configuration files
- ansible.builtin.import: configs.yml
  tags:
    - configs

# dependent packages and libs to be installed
- ansible.builtin.import: dependencies.yml
  tags:
    - dependencies

# ntp configurations
- ansible.builtin.import: ntp.yml
  tags:
    - ntp
    - chrony

# core software modules
- ansible.builtin.import: sdr.yml
  tags:
    - sdr

# tools and utilities
- ansible.builtin.import: tools.yml
  tags:
    - tools

# email setup
- ansible.builtin.import: email.yml
  when:
    - enable_email_push
  tags:
    - email

# twitter push setup
- ansible.builtin.import: twitter.yml
  when:
    - enable_twitter_push
  tags:
    - twitter
