---
- name: install chrony
  ansible.builtin.package:
    name: chrony
    state: present
  become: true

- name: ensure chrony is enabled and running
  ansible.builtin.service:
    name: chrony
    enabled: true
    state: started
  become: true

- name: write the ntp sources file
  ansible.builtin.template:
    src: ntp.sources.j2
    dest: /etc/chrony/sources.d/ntp.sources
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: reload chrony sources
...
