---
- name: install tweepy if twitter push is enabled
  ansible.builtin.pip:
    name: tweepy
    executable: pip3
    state: present
  become: true

- name: drop template twitter tweepy config file
  ansible.builtin.copy:
    src: tweepy.conf
    dest: "{{ ansible_user_dir }}/.tweepy.conf"
    owner: "{{ ansible_user_id }}"
    mode: '0600'
    force: false
...
