---
- name: install raspberry-noaa-v2 core
  hosts: core
  gather_facts: false
  pre_tasks:
    - name: gather facts
      ansible.builtin.setup:
        gather_subset: ['!all', 'min']
  roles:
    - role: common
